# Also see https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: Dependencies
    init: |
      sudo bash .github/workflows/ubuntu_20.04/build-deps.sh  # install deps
      sed "s/cd \/build/cd \/workspace\/gdal/1" -i .github/workflows/ubuntu_20.04/build.sh

      #bash .github/workflows/ubuntu_20.04/build.sh. # build
      # let's try cmake build instead
      # adapted from CONTRIBUTING.md#setting-development-environment-cmake-experimental
      mkdir build
      cd build
      cmake ..
      make -j8 -s
